ДЗ 1
mDayZZ/2024-2-VK-EDU-Frontend-M-Seregin pull request #1
Opened 2024-09-18 11:32 UTC by mDayZZ

# Домашнее задание №1

Прошу @martinkomitsky, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Реализованы функции convertBytesToHuman, correctSentence и nonUniqueElements
* Совершено покрытие тестами новых функций.

2024-09-19 15:04 UTC, RomanBarannickov requested changes

2024-09-19 15:04 UTC, RomanBarannickov commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(NaN)).toBe(false)
1. строка 13, 14, 16 - это тест на то, что тип аргумента функции строка. По факту они дублируют друг друга, оставь лучше один

2. В задание указано "Необходимо покрыть все возможные и невозможные кейсы.". Некоторые типы данных для проверки в тестах на входящий аргумент функции ты пропустил, подумай какие и добавь их.
 
3. отсутствует тест на передачу 0 аргументом, добавь его
 
P.s подсказка, посмотри весь список типов данных , которые существуют в js

2024-09-19 15:04 UTC, RomanBarannickov commented on correctSentence.js
> +}
1. никогда не стоит мутировать значение входящей функции, всегда стоит копировать входящие значения в переменную и уже с внутренней переменной работать

2. скорее всего забыл убрать console.log после дебага. Стоит убрать его

3. не забываем точки с пятой в конце строк. Это не только моя хотелка, но и в редких случая из за особенностей обработки кода, могут случиться непредвиденные ошибки, лучше этого сразу избежать, просто ставя точки с запятыми в конце строк кода

4. в конструкциях с if, так же используем скобки по возможности, они на самом деле увеличивают читабельность кода.

5. На строке 23 лишний пробел перед !text

6. Если я передам пустую строку, все ли будет нормально работать?

7. В рамках задачи нет такого, не обязательно к добавлению, но : Так как это JS, а не TS, на этапе разработки нет подсветки типов и в функцию в теории можно передать все что угодно, Я бы советовал добавить проверку на то, что входящий аргумент, действительно строка, что в теории в будущем избежать возможных проблем

2024-09-19 15:04 UTC, RomanBarannickov commented on convertBytesToHuman.js
> +}
страшна, вырубай!)

1. не кажется ли тебе, что код с строки 27 по 43, подозрительно похож на цикл?) Подумай как оптимизировать этот код и превратить его в цикл.

2. Для хранения порядков, предлагаю использовать какую нибудь структуру данных. А не прописывать грубо руками через if else как сделано на строках 45-57

3. Подсказка, для вывода строки посмотри в сторону шаблона строк. https://doka.guide/js/template-strings/

2024-09-19 15:04 UTC, RomanBarannickov commented on nonUniqueElements.js
> +      dataCounter[element] = 1;
1. можно убрать else и представить в виде 

if (...) {
   if logic;
   return;
}

else logic without else;

2024-09-20 13:02 UTC, RomanBarannickov approved these changes
@martinkomitsky, @kgrechin approve 
 
 @mDayZZ респект что внес все правки поданным рекомендациям, так держать!

2024-09-21 17:05 UTC, martinkomitsky approved these changes
12!

2024-09-21 17:06 UTC, merged