Exam
mDayZZ/2024-2-VK-EDU-Frontend-M-Seregin pull request #13
Opened 2024-12-23 18:32 UTC by mDayZZ

# Экзамен

Прошу @martinkomitsky, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Перевод при написании текста
* Дебаунс для отправки из формы
* Селекторы
* Пагинация
* Кэширование запросов
* Подключение реакт роутера

Что не было сделано:
* Деплой
* Стили не соответствуют макету
* История

2024-12-27 22:45 UTC, HaseProgram requested changes
Сделано много всего, очень классно, есть только пара мелких комментов.

Пока ставлю 38.
2 мелких бага поправить - будет 42.
4 балла снял за отсутствие тайпскрипта)

2024-12-27 22:45 UTC, HaseProgram commented on exam/src/services/translateService/translate/utils.js
> +        return `mt|${to}`;
Что за mt?  Из-за этого не работает автодетект

2024-12-27 22:45 UTC, HaseProgram commented on exam/src/components/Translator/Translator.jsx
> +                    <LanguageSelector languagesList={languagesList} langState={langTo} setLangState={setLangTo} excludeLang={langFrom}/>
Autodetect в таргете - это странно, надо бы фильтрануть

2024-12-27 22:46 UTC, HaseProgram commented
Еще нужно убрать из пр все, что связано с домашним заданием

2024-12-29 00:29 UTC, mDayZZ commented
* Убрал лишнее из PR
* Сделал фильтрацию для "to"
* убрал "mt", оставил замену на "Autodetect" при неопределенном значении
* Пофиксил баг с переполнением контента на главной странице

2024-12-30 00:47 UTC, HaseProgram approved these changes
Супер, обновил до 42)

2024-12-30 00:48 UTC, merged