ДЗ 2
mDayZZ/2024-2-VK-EDU-Frontend-M-Seregin pull request #2
Opened 2024-09-23 21:45 UTC by mDayZZ

# Домашнее задание №2

Прошу @martinkomitsky, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Предыдущее дз перемещено в папку homework1
* Развёрнут simple-chat
* Подключен scss в проект
* Адаптивная стилизация
* Отправка сообщений
* Сохранение сообщений
* Заготовка цветовых стилей под кастомные темы
* Рендер информации о чате из json (фейк апи с натяжкой)
* Динамическая дата в сообщениях (По отношению к настоящему времени)
* [Деплой на github Pages](https://mdayzz.github.io/2024-2-VK-EDU-Frontend-M-Seregin/)

2024-09-24 12:34 UTC, RomanBarannickov requested changes

2024-09-24 12:34 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +        </div>
всё ок, но давай добавим немного семантики
контейнер чат -> ui
элементы контейнер чата -> li

2024-09-24 12:34 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +<!--        <link rel="stylesheet" href="/fonts/MaterialSymbolsOutlined.ttf" />-->
удОлить закоментированный код

2024-09-24 12:34 UTC, RomanBarannickov commented on simple-chat/src/js/api.js
> +}
1. как ты описал - это аля апи, функции апи редко отдают JSON именно, обычно такие функции возвращают готовые к работе данные, объекты или массивы объектов, чтоб потом в каждом месте не парсить этот json и не делать одних и тех же действий. Лучший сразу на самом верхнем уровне получить сериализованные данные.

2. если это +- как апи, то лучше не возвращать сразу индекс 0 от массива. Если бы мы писали на TS, он бы сразу сказал, что в данном месте у тебя возвращаемый тип функции будет object | undefined. По этому лучше проверь, есть что возвращать или нет и если нет, то стоит добавить какую та явную обработку. Обычно всегда предпочтительнее использовать null. Т.к null - это конкретное значение пустоты, а undefined - это просто переменная у которой **не присвоено ** значение

3. Не забудь добавить в местах вызовах этих функций, обработку на undefined | null, а то может и не с чем работать будет

4. Факультатив, перепиши эти функции на промисы, чтоб данные получались с задержкой и доработай соответственно весь код в местах вызова

2024-09-24 12:34 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +}
не обязательно к исправлению
вроде везде писал на стрелочных, а тут бах и на обычных, почему?)

2024-09-24 12:34 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +})
не обязательно к исправлению
помимо подписки на событие, у есть и отписка от события. Отписка от события нужна, чтобы не происходила утечка памяти на код, который уже не нужен или не актуален для данной страницы. В данном случае, после того как событие отработало, в нем нет необходимости. У addEventListener есть 3 параметр с options в котором можно указать автоотписку после исполнения, параметр называется once 
скрин чтоб показать, что после исполнения, логика всё так же остается и требует на себя ресурсы клиента
![image](https://github.com/user-attachments/assets/d5b8547e-e608-43ce-a81e-9de0690b1b21)

2024-09-24 12:34 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    })
не обязательно к исправлению
1. всё круто, но при каждом проходе цикла, элемент сразу вставляется в родителя, что за собой тянет reflow и repaint в браузере, когда элементов мало, всё работает хорошо, но вот вопрос, на сколько всё будет хорошо работать, если сообщений в чате 100500 сообщений? можно все сделать одним разом, вставив все элементы чата в одину промежуточную ноду, а уже эту группу всю вставить непосредственно в чат. Используй [фрагмент](https://learn.javascript.ru/modifying-document#document-fragment)

2.updateMessages  используется каждый раз внутри sendMessage, и при добавление одного элементы, ты делаешь перерасчет всего массива, как не оптимально получается. Подумай над оптимизацией. Кажется, что код внутри цикла можно вынести в отдельную функцию и как то переиграть эту историю

2024-09-25 10:22 UTC, RomanBarannickov requested changes

2024-09-25 10:22 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +}
не обязательно к исправлению
чтоб уменьшить вложенность и увеличить читабельность лучше делать вот так
if (!chatInfo) {
    return;     
}

do something

2024-09-25 10:22 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +let memberInfo;
1. наверное лучше вынеси эти переменные перед всеми функциями, а то я еле смог найти их читая код выше и приходится прыгать по коду
2. Назначь им сразу начальное значение null, лучше так чем без значения

2024-09-25 10:22 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    chatInfo = await getChatById(1);
не обязательно к исправлению
вроде бы эти два запроса независимы друг от друга, можно их тоже через Promise.All сделать, чтоб они не ждали в теории друг друга и запросы выполнялись параллельно

2024-09-25 10:22 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    }
не обязательно
лучше использовать обратную проверку
если инфы о пользователе нет и нет инфы о чате, выходим из функции

так уменьшается вложенность

2024-09-25 10:22 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    let senderInfo = memberInfo.filter(member => member.id === senderId)[0];
вот снова эта штука)
в теории с определенной долей вероятности взяв индекс 0 от массива после фильтра, твое значение senderInfo = undefined
а потом senderInfo.id у тебя упадет с ошибкой потому что undefined.id нельзя обращаться, такого поля нет в сущности undefined

1. ты либо делай senderInfo?.id которая при значение senderInfo = undefined, выдаст просто undefined, а не упадет с ошибкой и твоя проверка на сравнение ниже пройдет, потому что будет undefined === userInfo.id
2. либо через if проверить, что значение в senderInfo присутствует
3. Это JS позволяет так написать, в реальных проектах почти везде TS, он бы на уровне типов уже бы кричал)
4. зачем let? вроде нет изменения переменной, лучше const в таких случаях

2024-09-25 10:22 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    const isSelf = senderInfo.id === userInfo.id;
тоже самое что и к комменту выше
если в одном из состояний приложения значения переменной userInfo может быть как null или undefined
ты либо обращайся через условный оператор userInfo?.id, чтоб приложение не упало с ошибкой, либо проверяй через if выше. 100% гарантировать при уже запущенном приложение, что сюда ну никак не может попасть null или другое неожиданное значение - гарантия бага)

2024-09-27 14:44 UTC, RomanBarannickov approved these changes
@mDayZZ Все круто!
 @martinkomitsky, @kgrechin апрув

2024-09-29 13:52 UTC, merged

2024-09-29 13:53 UTC, martinkomitsky commented
12!