ДЗ 3
mDayZZ/2024-2-VK-EDU-Frontend-M-Seregin pull request #3
Opened 2024-10-02 10:57 UTC by mDayZZ

# Домашнее задание №3
Прошу @martinkomitsky, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Разделение проекта на компоненты
* Рендеринг компонентов в JS.
* Реализация смены страниц, смены состояния приложения
* Изменение работы с localStorage, сохранение диалогов
* [Деплой на gh-pages](https://mdayzz.github.io/2024-2-VK-EDU-Frontend-M-Seregin/)

![Скриншот страницы с чатами](https://github.com/user-attachments/assets/c78c7072-c8b5-4330-a9d8-328b253b0faa)
![Скриншот страницы чата](https://github.com/user-attachments/assets/3a5fd8bf-78b5-4370-bceb-a4b3be5b2846)

2024-10-05 14:21 UTC, RomanBarannickov requested changes
всё очень круто но
вообще почти что отсутствует семантика в верстке
очень прошу пройтись и переверстать на семантическую верстку
всякие header, footer, main и так далее 
сайт в помощь.
https://doka.guide/html/semantics/
по js все классно, унифицируй повторяющиеся куски кода и будет вообще пушка

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/api.js
>  export const getUserById = (id) => {
1. посмотри в сторону async await. Код получиться более читабельный
касается всех твоих промисов

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/api.js
наверное стоило бы уже разделить этот файл на несколько. Функции для чата в одну сторону, функции для пользователя в другую. Плюс массивы с замоканными данными положить рядом в файлик мок

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/chatContainer/index.js
> +        const [messageElement, children] = createMessageElement({userId, message})
children есть, а нигде вроде не используется

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/chatForm/index.js
> +                const chatsFromLocal = JSON.parse(localStorage.getItem('chats')) || [];
получение данных из локал стораджа и его парсинга с фалбеком в виде пустого массива, вы неси в отдельную функцию, чтоб можно было переиспользовать

в целом я бы логику обновления чата вынес бы так же в отдельную функцию

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/chatForm/index.js
> +                    localStorage.setItem('chats', JSON.stringify(chatsFromLocal));
запись в локал сторадж, тоже лучше вынести в отдельную функцию

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/chatForm/index.js
> +        const messageId = Math.floor(Math.random() * (100000 - 1)) + 1;
так же лучше вынести в отдельную функцию хелпер по генерации уникальных ключей
вдруг потом заменишь на библиотеку, чтоб потом не бегать по всему коду не искать такие вставки

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/chatHeader/index.js
> +    const chatHeaderElement = createElement('div', 'header chatHeader');
семантикааааааааааа
https://doka.guide/html/semantics/

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/chatHeader/index.js
> +    return [chatHeaderElement, {...chatInfoChildren, ...actionContainerChildren}];
кстати возвращать можно объекты сразу а не массивами, мне кажется удобней будет работать

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/chatHeader/index.js
> +    const [chatInfoElement, chatInfoChildren] = createChatInfo();
не очень хорошо использовать функции до их объявления
лучше объяви сначала все вспомогательные функции
и потом уже последней ту, которая использует их
чтоб сверху вниз была логика

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/pages/chatActivity.js
> +    const container = createElement('div', 'container');
https://doka.guide/html/semantics/
main

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/pages/chatActivity.js
> +        const chatInfo = chatsFromLocal.find(chat => Number(chat.id) === Number(chatId));
лучше как то в отдельную функцию логику получения чата из стораджа и поиска его

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/utils/createElements.js
> +    }
норм но чего foreach не устроил?)

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/conversationHeader/index.js
> +    const conversationHeaderElement = createElement('div', 'header conversationHeader');
https://doka.guide/html/semantics/

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/conversationHeader/_conversationHeader.scss
что за пустое значение?

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/conversationList/index.js
> +    const chatsFromLocal = JSON.parse(localStorage.getItem('chats'));
уже не первое место получения чата из локал стораджа и его парсинг, а если будем хранить не в локалсторадже, а на беке, везде бегать менять это руками вместо того чтоб в одном месте поменять?

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/components/conversationList/index.js
> +    }
этот блок я вообще один в один видел в коде, надо это значит логику вынести если она повторяется

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/pages/chatActivity.js
> +    const chatsFromLocal = JSON.parse(localStorage.getItem('chats'));
и снова эта логика

2024-10-05 14:21 UTC, RomanBarannickov commented on simple-chat/src/js/pages/conversationActivity.js
> +    const container = createElement('div', 'container');
https://doka.guide/html/semantics/

2024-10-05 14:23 UTC, RomanBarannickov commented
плюс 
по архитектуре папок 
я бы уже отходил от подхода с папкой js, css и так далее
лучше сделать тип того
src
------index.js
------index.scss
------components
------------component1
------------------------index.js
------------------------styles.scss

я видел ты уже так начал делать кое где, сделай так со всеми компонентами

2024-10-06 20:06 UTC, mDayZZ commented on simple-chat/src/js/components/conversationList/index.js
> +    const chatsFromLocal = JSON.parse(localStorage.getItem('chats'));
Я вынес отдельно в функцию getChats, но, не сильно уверен, что стоило. Нашёл, получение из локал стораджа в chatForm для того, чтобы в дальнейшем добавить новое сообщение и удалить его, но как будто бы там оправдано... В общем не очень понял, как правильнее было бы решить... Как вариант можно было бы в index.js в глобальную переменную внутри window. класть значение из localStorage и взаимодействовать с ней, но стоит ли?

2024-10-08 11:32 UTC, RomanBarannickov approved these changes
@martinkomitsky, @kgrechin
апрув

2024-10-09 07:54 UTC, HaseProgram approved these changes
Супер! 12

2024-10-09 07:54 UTC, merged