ДЗ №5
mDayZZ/2024-2-VK-EDU-Frontend-M-Seregin pull request #5
Opened 2024-10-21 15:53 UTC by mDayZZ

# Домашнее задание №5

Прошу @martinkomitsky, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* Перевод проекта на React + Vite
* Применение контекст хуков для реализации в дальнейшем функции смены и создания кастомных тем
* Моковая БД с эмуляцией бэкенд ручек, вывод взаимоотношений с бэкендом в services
* Применение .env переменных
* Коррекция gh-actions workflow
* [Деплой на gh-pages](https://mdayzz.github.io/2024-2-VK-EDU-Frontend-M-Seregin/#/chats)

2024-10-22 10:39 UTC, RomanBarannickov requested changes
как всегда сильная работа, но есть на что обратить внимание
1. уже никак факультатив. Необходимо чтоб была возможность добавить новый чат, а то сейчас все достаточно статично
2. должен быть поиск\фильтрация списка чатов
3. обрати внимание, после выбора чата и переход на страницу сообщений, какой есть лаг появления аватарки и имени чата, надо бы как то докрутить чтоб это по быстрее работало
4. обрати внимание на вложенности с if, которые ты пишешь, постарайся избегать вложенности и по возможности делать обратные проверки, код станет чище
5. по Поводу моков в твоих. Возвращай какое то внятное значение из своих функций. Тип если ожидается объект, верни как заглушку просто null. Если массив - пустой массив. Возвращать undefined или ничего не возвращать не очень хорошо
6. Холиварный момент по поводу выброса исключения. Тут конечно как в проекте заведено, но в среднем выкидывать исключение надо когда прям вообще какой треш произошел и надо остановить работу приложение. В среднем лучше вывести какой то console error и типобезопасный ответ функции, типа null или пустой массив. Просто выброс исключения и его не правильная обработка может привести к крашу приложения на проде, с этим стоит быть аккуратно

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/.gitignore
загугли шаблон целый для gitignore для web разработки, тогда не понадобиться на каждый чих править этот файл

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +    const [userInfo, setUserInfo] = useState({});
лучше использовать null тогда как значение инициализации. Так хотя бы как то можно понять, в каком состояние находится информация о пользователе

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/assets/react.svg
а оно надо где то?

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/ChatHeader/ChatHeader.jsx
> +    const HeaderClasses = ['chatHeader', className, classes.chatHeader].join(' ').trim();
1. переменная с малой буквы
2. я думаю никто не будет против если подключишь библиотеку [classnames](https://www.npmjs.com/package/classnames), чтоб удобней было работать с классами

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/ConversationItem/ConversationItem.jsx
> +                    <p className={classes.conversationItem__name}>{chatTitle}</p>
если это title, может быть тогда стоит присмотреться к какому то более семантическому тегу. Типа какой то вариант h тега

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/MessageForm/MessageForm.jsx
> +        }
сделай обратные проверки чтоб убрать вложенность

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/MessageList/MessageList.jsx
> +                :   <h2 style={{alignSelf: "center", justifySelf: "center"}}>Сообщений пока нет :(</h2>
вынеси в стили. Инлайново стили писать можно когда вообще никаких вариантов больше нет

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/MessageList/MessageList.jsx
> +        <ul className={classes.messageList} style={{backgroundColor: theme.chatBackgroundColor, color: textColor}}>
кажется вопрос передачи темы можно решить более красивым методом через custom prop css и js 
https://doka.guide/js/element-set-property/

конечно через style рабочая схема, но кажется было бы красивее через js и css

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/UI/DefaultButton/DefaultButton.jsx
> +const DefaultButton = ({children, color, onClick}) => {
лучше просто button кажется назвать. default как то о чем то не говорит
передавай так же тип кнопки обязательно

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/UI/IconButton/IconButton.jsx
> +        <button className={classes.iconButton} onClick={onClick} style={{'color': color}}>
type у button

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +    const [chatInfo, setChatInfo] = useState({});
лучше null как начальное состояние

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +        <div className={'page'}>
у тебя вроде бы module css, зачем использовать глобальные стили тогда?

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/contexts/ThemeContext.jsx
напиши тут сразу кастомный хук
типа 
useTheme = useContext(ThemeContext)
и используй этот хук уже в компонентах место того, чтоб везде импортировать контекст конкретный
так удобней будет и если что контекст можно будет без бозболезненно сменить

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/hooks/useChatInfo.js
> +        };
делай инверсию проверок
`if (!chatInfo.id) {
 return;
}`

у тебя весь этот блок можно написать без вложенности вообще и без else

меньеш вложенность - выше читабельность

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/hooks/useChatInfo.js
> +    }, [chatInfo, userId]); // Выполняем при изменении chatInfo или userId
такие комментарии бессмысленны
они не несут никакой ценности для понимания кода

2024-10-22 10:39 UTC, RomanBarannickov commented on react-chat/src/styles/_globals.scss
> +.page {
нууууу не очень что ли хорошо иметь глобальные стили вот так
лучше такие штуки как то на компонентом подходе решать

типа все страницы имеют компонент page в котором скрыт данный css
как то так, но не глобальными стилями

2024-10-22 10:42 UTC, RomanBarannickov commented
+ 
было бы круто, чтоб при заходе на страницу чата с сообщениями, сразу появлялся фокус на импуте

2024-10-27 04:28 UTC, mDayZZ commented on react-chat/src/components/MessageList/MessageList.jsx
> +    const { theme } = useContext(ThemeContext);
Имеет место быть такая реализация через customProp?

2024-10-30 14:20 UTC, RomanBarannickov requested changes
в целом всё не плохо. Комментарии мои в основном рекомендательные
главное сейчас почини демку и будет после этого апрув
рекомендации можно в некст домашках сделать

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/ChatHeader/ChatHeader.jsx
> +            </div>
выносим всю логику из jsx В переменные

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/ConversationItem/ConversationItem.jsx
> +    const conversationLastMessage = `${conversation.last_message?.user?.username}: ${conversation.last_message?.content}` || 'Сообщений пока нет';
conversation.last_message?.user?.username - когда используешь такую штуку
внутри строчного теплейта, там вроде может быть момент, что в итоге внутри строки будет написано undefined
потому что условная цепочка возвращаешь undefined, если объекта нет

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/ConversationList/ConversationList.jsx
> +            }
1. компонент в react само закрывающиеся то есть не надо писать <UserListItem></UserListItem> если нет children
лучше писать <UserListItem />

2. можно просто тогда указать searchQuery && <Component/>

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/ConversationList/ConversationList.jsx
> +            const searchTerms = searchQuery.toLowerCase().split(' ').filter(Boolean);
не уверен, но кажется именно тут ошибка. Кажется я уже упоминал об осторожности с параметрами из url. Их всегда надо проверять
![image](https://github.com/user-attachments/assets/9dff2f9c-3450-4b81-883e-d21fcd20d73a)

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/ConversationsFinder/ConversationsFinder.jsx
> +        <FinderInput className={classes.conversationsFinder} value={searchQuery} onInput={(event) => setSearchQuery(event.target.value)}/>
1. выносим логику функции onInput в отдельную функцию. В jsx как можно меньше должно быть логики

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/ConversationsFinder/ConversationsFinder.module.scss
если не надо, то удали. ПУстые классы не несут полезной нагрузки

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/ConversationsHeader/ConversationsHeader.jsx
> +            <ConversationsFinder searchQuery={searchQuery} setSearchQuery={setSearchQuery}></ConversationsFinder>
уже писал про самозакрывающиеся теги. Выше ты для Menu используешь, а тут то почему нет

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/MessageItem/MessageItem.jsx
> +        document.documentElement.style.setProperty('--message-text-color', textColor);
лайк

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/MessageItem/MessageItem.jsx
> +                <p className={classes.message__datetime}>{getDatetime(message.created_at)}</p>
ну вот каждый пункт можно вынести в переменную и уже конечные переменные использовать в jsx
чтоб UI было прям вообще все равно откуда у тебя данные
сам подставил или из объекта с выше свалились

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/UI/RoundAvatar/RoundAvatar.jsx
> +        <img className={avatarClasses} src={src ? src : 'images/avatars/default_avatar.png'} onError={(e) => {
onError в функцию отдельную
src можно указать вот так src ?? 'images/avatars/default_avatar.png
а лучше тогда уж дефолтное значение на строке 4 поменял с null на вот эту константу пути к дефолтной картинке 
({src: DEFAULT_AVATAR_PATH}) типа того

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/UI/UserListItem/UserListItem.jsx
> +                    <h2 className={classes.userListItem__name}>{heading || '...'}</h2>
в отдельную переменную

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +        console.log('fromfetc', fetchedChatInfo)
какой то забытый дебаг

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/components/pages/ConversationsPage/ConversationsPage.jsx
> +            <ConversationsHeader searchQuery={searchQuery} setSearchQuery={setSearchQuery} className={classes.conversationsPage__header} />
не надо передавать в компоненты сразу сеттер от useState. Это сильно обязывает, особенно если писать код на TS
лучше передавать функцию обертку которая примет значение и передаст потом в setter от useState
сегодня у тебя локальный стейт, завтра глобальный стор какой то
вместо того, чтоб поменять внутренности одной функции и забыть про это, придется менять и типы и функцию другую передавать

лучше всегда просто обертки передавать, а внутри оберток уже делать свою логику

2024-10-30 14:20 UTC, RomanBarannickov commented on react-chat/src/services/chatService.js
> +}
ну вот тебе не кажется что это всё выглядит как то туматч?

1. твоя функция имеет побочные эффекты. Не должна функция которая отвечает за то, чтоб отдать чат по id что то класть ещё в локал сторадж
2. Просто отсюда возвращай сейчас то, что у тебя лежит в локалсторадже, потом заменишь на вызов апи с бека и всё
3. убери эти все флаги. Пользы от них толковой нет, только читать сложнее этот код.
4. Получать чат по userId имхо странно. Надо получать чат по собственному личному айди. Конечно если подумать что связь чата и какого то контакта 1 к 1. Но всё же было бы предпочтительнее получать чат по id самого чата, а не по косвенному признаку id контакта

эти рекомендации относятся ко всем строка где куча ифов с мок не мок и все такое. Не усложняй

2024-10-31 00:13 UTC, mDayZZ commented
Домашка не отображается без чистки local storage. Честно говоря затрудняюсь с реализацией избежания этой проблемы, но я менял структуру данных внутри локалки и появился вопрос по поводу того, как грамотно проверять валидность сохранённых данных...

2024-10-31 10:53 UTC, RomanBarannickov approved these changes
@martinkomitsky, @kgrechin
 апрув

2024-11-05 06:51 UTC, martinkomitsky commented
12!

2024-11-05 06:51 UTC, merged