Домашнее задание №7
mDayZZ/2024-2-VK-EDU-Frontend-M-Seregin pull request #7
Opened 2024-11-09 16:43 UTC by mDayZZ

# Домашнее задание №7

Прошу @martinkomitsky, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
* 
* 
*

2024-11-10 08:43 UTC, RomanBarannickov requested changes

2024-11-10 08:43 UTC, RomanBarannickov commented on react-chat/src/services/api/users/index.js
> +    get: (params) => apiService.get(`/users`, params),
ну слишком аскетично чет. хотя бы getUserList ну гет запросов может быть вагон и маленькая тележка

2024-11-10 08:43 UTC, RomanBarannickov commented on react-chat/src/contexts/AuthContext.jsx
> +        user,
не надо смешивать в одну кучу всё всё таки
данные о пользователе - это одно
данные об авторизации этого пользователя уже немного другое

2024-11-10 08:43 UTC, RomanBarannickov commented on react-chat/src/contexts/AuthContext.jsx
> +            await fetchUserData();
вот это всё можно поместить в какой нибудь authService который всё сделает. Чтоб этим не занимался компонент и вернуть из одного метода. Какие надо данные для ui  и всё

2024-11-10 08:43 UTC, RomanBarannickov commented on react-chat/src/contexts/AuthContext.jsx
> +        TokenService.clearTokens();
тоже самое в сервис авторизации это спрячь. Не надо всему приложению знать как и где с токенами работать

2024-11-10 08:43 UTC, RomanBarannickov commented on react-chat/src/contexts/AuthContext.jsx
> +            }
тоже самое - это можно попробовать инкапсулировать внутри отдельного сервиса авторизации

2024-11-11 22:57 UTC, mDayZZ commented on react-chat/src/contexts/AuthContext.jsx
> +        TokenService.clearTokens();
Вот с созданием сервиса авторизации у меня вопросы возникли. Не понимаю, как нам оттуда делать редирект. navigate же можно только в компонентах использовать, а напрямую через window врядли правильно

2024-11-16 08:15 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin 
апрув

@mDayZZ Всё круто. Мне особо даже нечего сказать

2024-11-16 08:15 UTC, RomanBarannickov commented on react-chat/src/components/pages/AuthPage/AuthPage.jsx
разнеси эту страницу лучше на две страницы. auth и register. зачем все в один компонент всё складывать

2024-11-16 08:15 UTC, RomanBarannickov commented on react-chat/src/components/UserProfile/UserProfile.jsx
> +    // let profileUsername = `@${info.username}`;
всё это удаляем. Всю историю и так помнит гит

2024-11-19 15:06 UTC, merged

2024-11-19 15:07 UTC, martinkomitsky commented
10!