Домашнее задание №8
mDayZZ/2024-2-VK-EDU-Frontend-M-Seregin pull request #8
Opened 2024-11-17 01:18 UTC by mDayZZ

# Домашнее задание №8

Прошу @martinkomitsky, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:
*
*
*

2024-11-24 17:04 UTC, RomanBarannickov requested changes
1. При добавление нового чата. Не происходит подгрузка актуальных чатов. Либо надо мутировать имеющиеся чаты, либо при добавление нового чата, надо дергать апишку всех чатов
2. нет уведомлений, когда пришло сообщение из другого чата

2024-11-24 17:04 UTC, RomanBarannickov commented on react-chat/src/components/AttachedFileList/AttachedFileList.jsx
> +                attachedFiles.map((attachedFile, index) => <AttachedFileItem attachedFile={attachedFile} onDeleteFile={onDeleteFile} index={index}  key={index} />)
использовать index как key. Плохая история. Попробуй найти какой то id уникальный от самого файла или тип того

2024-11-24 17:04 UTC, RomanBarannickov commented on react-chat/src/components/MessageFileItem/MessageFileItem.jsx
> +        let fileUrl = file;  // предполагаем, что file содержит URL для скачивания
а если не содержит?
что значит предполагаем?
надо проверять на верника, что file пришел, а если ты не уверен, то лучше проверить

2024-11-24 17:04 UTC, RomanBarannickov commented on react-chat/src/components/MessageFileItem/MessageFileItem.jsx
> +        document.body.removeChild(link);  // удаляем ссылку после скачивания
комментарии ради комментариев. Они не несут полезной нагрузки

2024-11-24 17:04 UTC, RomanBarannickov commented on react-chat/src/components/pages/ChatPage/ChatPage.jsx
> +        <Page onDragEnter={onDragEnter} onDragLeave={onDragLeave} onDragOver={onDragOver} onDrop={onDrop}>
если твои поля объекта совпадают с названием пропсов компонента можно использовать деструктуризацию
<Page {...dragAndDropProps} />

2024-12-04 15:01 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув

2024-12-07 10:35 UTC, HaseProgram commented
Аппрув, 10!

2024-12-07 10:35 UTC, merged